services:
  postgres:
    container_name: "whooshpostgres"
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      WHOOSHPOSTGRES_VERSION: "11.0.0"
      USERS: "admin,name"
      INDEXATION: true
      PARTITION_ORDERS: true
      BACKUPS_ALLOWED: 5
      BACKUP_FREQUENCY: 12
      DO_BACKUP: true
    volumes:
      - ./migrations:/migrations/
      - ./indexations:/indexations/
      - ./partitions:/partitions/
      - ./backup:/backup/
      - whooshpostgres-data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"


volumes:
  whooshpostgres-data: